apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: my-project
  source:
    repoURL: https://github.com/kimabigal/project_AKS.git
    targetRevision: main
    path: app-api/helm-api
    helm:
      values: |
        image:
          repository: myacr12067.azurecr.io/api-app
          tag: "latest"
        deployment:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
