apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  MYSQL_USER:          {{ .Values.auth.user | quote }}
  MYSQL_PASSWORD:      {{ .Values.auth.password | quote }}
  MYSQL_DATABASE:      {{ .Values.auth.database | quote }}
