apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_ROOT_PASSWORD } }
        - name: MYSQL_DATABASE
          valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_DATABASE } }
        - name: MYSQL_USER
          valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_USER } }
        - name: MYSQL_PASSWORD
          valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_PASSWORD } }
        ports:
        - containerPort: {{ .Values.service.port }}
        readinessProbe:
          exec: { command: ["bash","-lc","mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD"] }
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          exec: { command: ["bash","-lc","mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD"] }
          initialDelaySeconds: 30
          periodSeconds: 20
        resources: {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata: { name: data }
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      {{- if .Values.persistence.storageClassName }}
      storageClassName: {{ .Values.persistence.storageClassName | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}